CREATE TABLE [dbo].[USUARIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORA] [time](7) NOT NULL,
	[RAMAL_TEL] [varchar](15) NULL,
	[NOME_USUARIO] [varchar](500) NULL,
	[PREDIO_SETOR] [varchar](200) NULL,
	[ATIVO] [varchar](10) NULL,
	[DATA_DES] [date] NULL,
	[HORA_DES] [time](7) NULL,
	[OBS_GERAL] [ntext],

 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


