CREATE TABLE [dbo].[TECNICOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORA] [time](7) NOT NULL,
	[NOME_COMPLETO] [char](200) NULL,
	[DRT_ID] [char](50) NULL,
	[EMAIL] [char](50) NULL,
	[SENHA] [char](50) NULL,
	[ATIVO] [varchar](10) NULL,
	[DATA_DES] [date] NOT NULL,
	[HORA_DES] [time](7) NOT NULL,
	
 CONSTRAINT [PK_TECNICOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


