USE [db_ab2460_helpdesk02]
GO

/****** Object:  Table [dbo].[MOVI_RETIRADA]    Script Date: 01/07/2026 08:01:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOVI_RETIRADA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORA] [time](7) NOT NULL,
	[ESTAGIO] [char](200) NULL,
	[RAMAL_TEL] [varchar](15) NULL,
	[NOME_USUARIO] [varchar](500) NULL,
	[PREDIO_SETOR] [varchar](200) NULL,
	[AREA] [varchar](15) NULL,
	[NUMERO_OS] [nvarchar](50) NULL,
	[EQUIPAMENTO] [nvarchar](50) NULL,
	[SAI] [nvarchar](50) NULL,
	[SSD] [nchar](10) NULL,
	[OFFICE_365] [nchar](10) NULL,
	[MAINFRAME] [nchar](10) NULL,
	[CNS] [nchar](10) NULL,
	[BOTAO_EMERGENCIA] [nchar](10) NULL,
	[OFFICE_365_PLAN] [nchar](10) NULL,
	[DESCRICA_ATIVIDADE] [ntext] NULL,
	[OBS_IMPORTANTES] [ntext] NULL,
	[PATRIMONIO] [nvarchar](50) NULL,
	[TECNICO_SOLICITANTE] [varchar](500) NULL,
	[TECNICO_ATUANTE] [varchar](500) NULL,
	[DATA_RETIRADA] [date] NULL,
	[HORA_RETIRADA] [time](7) NULL,
	[SITUACAO] [nchar](50) NULL,
	[MODALIDADE] [nchar](30) NULL,
	[PRIORIDADE] [nchar](30) NULL,
	[DATA_PREVISTA] [date] NULL,
	[HORA_PREVISTA] [time](7) NULL,


 CONSTRAINT [PK_MOVI_RETIRADA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


