CREATE TABLE [dbo].[EQUIPAMENTOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORA] [time](7) NOT NULL,
	[DESCRICAO_EQUIPAMENTO] [char](200) NULL,
	[ATIVO] [varchar](10) NULL,
	[DATA_DES] [date] NULL,
	[HORA_DES] [time](7) NULL,
	
 CONSTRAINT [PK_EQUIPAMENTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


