CREATE TABLE [dbo].[MOVI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORA] [time](7) NOT NULL,
	[ESTAGIO] [char](200) NULL,
	[RAMAL_TEL] [varchar](15) NULL,
	[NOME_USUARIO] [varchar](500) NULL,
	[PREDIO_SETOR] [varchar](200) NULL,
	[AREA] [varchar](15) NULL,
	[NUMERO_OS] [nvarchar](50) NULL,
	
 CONSTRAINT [PK_MOVI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


