USE [db_ab2460_helpdesk02]
GO

/****** Object:  View [dbo].[VIEW_MOVI_MOVI_RETIRADA]    Script Date: 01/07/2026 14:21:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_MOVI_MOVI_RETIRADA]
AS
SELECT        TOP (100) PERCENT dbo.MOVI.ID, dbo.MOVI.DATA, dbo.MOVI.HORA, dbo.MOVI.ESTAGIO, dbo.MOVI.RAMAL_TEL, dbo.MOVI.NOME_USUARIO, dbo.MOVI.PREDIO_SETOR, dbo.MOVI.NUMERO_OS, dbo.MOVI_RETIRADA.SITUACAO, 
                         dbo.MOVI_RETIRADA.PATRIMONIO, dbo.MOVI_RETIRADA.SAI, dbo.MOVI_RETIRADA.TECNICO_SOLICITANTE, dbo.MOVI_RETIRADA.TECNICO_ATUANTE, dbo.MOVI_RETIRADA.DATA_RETIRADA, 
                         dbo.MOVI_RETIRADA.HORA_RETIRADA, dbo.MOVI_RETIRADA.MODALIDADE, dbo.MOVI_RETIRADA.PRIORIDADE, dbo.MOVI_RETIRADA.DATA_PREVISTA, dbo.MOVI_RETIRADA.HORA_PREVISTA
FROM            dbo.MOVI INNER JOIN
                         dbo.MOVI_RETIRADA ON dbo.MOVI.ID = dbo.MOVI_RETIRADA.ID_RETIRADA
WHERE        (dbo.MOVI.ESTAGIO = 'RETIRADA DE EQUIPAMENTO')
ORDER BY dbo.MOVI.ID
GO

